# Generated by Django 2.2.5 on 2019-10-24 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_auto_20191023_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='size',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
