# Generated by Django 2.2.5 on 2019-09-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elbow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(choices=[('ElbowLight', 'درزدار سبک'), ('ElbowHeavy', 'درزدار سنگین'), ('Mannesmann', 'مانیسمان'), ('Type40', 'رده چهل')], max_length=100)),
                ('size', models.DecimalField(choices=[(2, '2 اینچ'), (2.5, '2.5 اینچ'), (3, '3 اینچ'), (4, '4 اینچ'), (5, '5 اینچ'), (6, '6 اینچ'), (7, '7 اینچ'), (8, '8 اینچ'), (10, '10 اینچ'), (12, '12 اینچ'), (14, '14 اینچ'), (16, '16 اینچ')], decimal_places=1, max_digits=2)),
                ('price', models.IntegerField()),
                ('number', models.IntegerField(choices=[(350, 350), (250, 250), (170, 170), (130, 130), (110, 110), (55, 55), (30, 30), (25, 25), (15, 15), (8, 8), (5, 5)], null=True)),
            ],
        ),
    ]
