# Generated by Django 2.2.5 on 2019-09-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zanoei', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='elbow',
            name='کیر',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
