# Generated by Django 2.2.5 on 2019-09-26 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zanoei', '0002_elbow_کیر'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elbow',
            old_name='number',
            new_name='تعداد_کیسه',
        ),
        migrations.RenameField(
            model_name='elbow',
            old_name='size',
            new_name='سایز',
        ),
        migrations.RenameField(
            model_name='elbow',
            old_name='price',
            new_name='قیمت',
        ),
        migrations.RenameField(
            model_name='elbow',
            old_name='model',
            new_name='مدل',
        ),
        migrations.RemoveField(
            model_name='elbow',
            name='کیر',
        ),
    ]
