# Generated by Django 2.2.5 on 2019-09-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zanoei', '0003_auto_20190926_0434'),
    ]

    operations = [
        migrations.AddField(
            model_name='elbow',
            name='name',
            field=models.CharField(choices=[('elbow', 'زانویی')], default='elbow', max_length=100),
        ),
    ]
