# Generated by Django 2.2.5 on 2019-09-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zanoei', '0004_elbow_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elbow',
            name='مدل',
            field=models.CharField(choices=[('darzdar', 'درزدار '), ('standard', 'استاندارد'), ('mannesmann', 'مانیسمان'), ('type40', 'رده چهل')], max_length=100),
        ),
    ]
