# Generated by Django 2.2.5 on 2019-11-01 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sold',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('بررسی_شده', models.BooleanField(default=False)),
                ('ارسال_شده', models.BooleanField(default=False)),
                ('پرداخت_چکی', models.BooleanField(default=False)),
                ('تاریخ_خرید', models.DateTimeField(auto_now=True)),
                ('کد_پیگیری', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
