# Generated by Django 2.2.6 on 2019-11-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sold', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sold',
            name='کد_پیگیری',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
