# Generated by Django 2.2.5 on 2019-09-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cap',
            name='name',
            field=models.CharField(choices=[('elbow', 'زانویی'), ('tee', 'سه راهی'), ('nippel', 'سردنده'), ('cap', 'کپ'), ('reducer', 'تبدیل')], default='elbow', max_length=100),
        ),
    ]
