# Generated by Django 2.2.5 on 2019-09-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap', '0002_cap_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cap',
            name='name',
            field=models.CharField(choices=[('cap', 'کپ')], default='cap', max_length=100),
        ),
    ]
