# Generated by Django 2.2.5 on 2019-10-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap', '0004_auto_20190927_0703'),
    ]

    operations = [
        migrations.AddField(
            model_name='cap',
            name='تصویر',
            field=models.ImageField(choices=[('images/cap.jpg', '1')], null=True, upload_to='photos'),
        ),
    ]
