# Generated by Django 2.2.5 on 2019-10-17 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cap', '0005_cap_تصویر'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cap',
            name='تصویر',
        ),
    ]
