# Generated by Django 2.2.5 on 2019-09-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('مدل', models.CharField(choices=[('Tee', 'درزدار'), ('Mannesmann', 'مانیسمان'), ('Type40', 'رده چهل')], max_length=100)),
                ('سایز_اصلی', models.DecimalField(choices=[(2, '2 اینچ'), (2.5, '2.5 اینچ'), (3, '3 اینچ'), (4, '4 اینچ'), (5, '5 اینچ'), (6, '6 اینچ'), (7, '7 اینچ'), (8, '8 اینچ'), (10, '10 اینچ'), (12, '12 اینچ'), (14, '14 اینچ'), (16, '16 اینچ')], decimal_places=1, max_digits=2)),
                ('سایز_انشعاب', models.DecimalField(choices=[(2, '2 اینچ'), (2.5, '2.5 اینچ'), (3, '3 اینچ'), (4, '4 اینچ'), (5, '5 اینچ'), (6, '6 اینچ'), (7, '7 اینچ'), (8, '8 اینچ'), (10, '10 اینچ'), (12, '12 اینچ'), (14, '14 اینچ'), (16, '16 اینچ')], decimal_places=1, max_digits=2)),
                ('قیمت', models.IntegerField()),
                ('تعداد_کیسه', models.IntegerField(choices=[(300, 300), (200, 200), (120, 120), (100, 100), (90, 90), (50, 50), (30, 30), (20, 20), (15, 15)], null=True)),
            ],
        ),
    ]
