# Generated by Django 2.2.5 on 2019-09-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tee',
            name='name',
            field=models.CharField(choices=[('tee', 'سه راهی')], default='tee', max_length=100),
        ),
    ]
