# Generated by Django 2.2.5 on 2019-09-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nippel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nippel',
            name='name',
            field=models.CharField(choices=[('nippel', 'سردنده')], default='nippel', max_length=100),
        ),
    ]
