# Generated by Django 2.2.5 on 2019-10-21 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.CharField(default='etesal', max_length=60, verbose_name='company name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='vip',
            field=models.BooleanField(default=False),
        ),
    ]
