# Generated by Django 2.2.5 on 2019-10-30 17:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('عنوان', models.CharField(max_length=255)),
                ('توضیحات', models.TextField()),
                ('تصویر', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('تاریخ_انتشار', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
